spring:
  application:
    name: lavanda-automated-download-shows
  profiles:
    active: dev   
cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false  
    sqs:
      endpoint:
        uri:
          transmission: https://sqs.eu-west-1.amazonaws.com/836783797541/transmission