spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OKTA_OAUTH2_ISSUER}/v1/keys
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 2
        #   max-interval: 10s
          multiplier: 2        
logging:
  level: 
    org:
      springframework: INFO